package mx.att.digital.customermanagement.interfaces.dto;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import mx.att.digital.customermanagement.interfaces.dto.AttachmentMVO;
import mx.att.digital.customermanagement.interfaces.dto.AttachmentRefMVO;
import mx.att.digital.customermanagement.interfaces.dto.Quantity;
import mx.att.digital.customermanagement.interfaces.dto.TimePeriod;
import java.io.Serializable;
import java.time.OffsetDateTime;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import jakarta.annotation.Generated;


@JsonIgnoreProperties(
  value = "@type", // ignore manually set @type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the @type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = AttachmentMVO.class, name = "Attachment"),
  @JsonSubTypes.Type(value = AttachmentRefMVO.class, name = "AttachmentRef"),
  @JsonSubTypes.Type(value = AttachmentRefMVO.class, name = "AttachmentRef_MVO"),
  @JsonSubTypes.Type(value = AttachmentMVO.class, name = "Attachment_MVO")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.10.0")
public interface AttachmentRefOrValueMVO extends Serializable {
    public String getAtType();
}
