package mx.att.digital.customermanagement.interfaces.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;

import java.io.Serializable;
import java.util.Objects;

/**
 * ContactMediumMVO
 */

@JsonIgnoreProperties(
  value = "@type", // ignore manually set @type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the @type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = ContactMediumMVO.class, name = "ContactMedium"),
  @JsonSubTypes.Type(value = EmailContactMediumMVO.class, name = "EmailContactMedium"),
  @JsonSubTypes.Type(value = FaxContactMediumMVO.class, name = "FaxContactMedium"),
  @JsonSubTypes.Type(value = GeographicAddressContactMediumMVO.class, name = "GeographicAddressContactMedium"),
  @JsonSubTypes.Type(value = PhoneContactMediumMVO.class, name = "PhoneContactMedium"),
  @JsonSubTypes.Type(value = SocialContactMediumMVO.class, name = "SocialContactMedium")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.10.0")
public class ContactMediumMVO implements Serializable {

  private static final long serialVersionUID = 1L;

  private Boolean preferred;

  private String contactType;

  private TimePeriod validFor;

  public ContactMediumMVO preferred(Boolean preferred) {
    this.preferred = preferred;
    return this;
  }

  /**
   * If true, indicates that is the preferred contact medium
   * @return preferred
   */
  
  @Schema(name = "preferred", description = "If true, indicates that is the preferred contact medium", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("preferred")
  public Boolean getPreferred() {
    return preferred;
  }

  public void setPreferred(Boolean preferred) {
    this.preferred = preferred;
  }

  public ContactMediumMVO contactType(String contactType) {
    this.contactType = contactType;
    return this;
  }

  /**
   * Type of the contact medium to qualify it like pro email / personal email. This is not used to define the contact medium used.
   * @return contactType
   */
  
  @Schema(name = "contactType", description = "Type of the contact medium to qualify it like pro email / personal email. This is not used to define the contact medium used.", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("contactType")
  public String getContactType() {
    return contactType;
  }

  public void setContactType(String contactType) {
    this.contactType = contactType;
  }

  public ContactMediumMVO validFor(TimePeriod validFor) {
    this.validFor = validFor;
    return this;
  }

  /**
   * Get validFor
   * @return validFor
   */
  @Valid 
  @Schema(name = "validFor", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("validFor")
  public TimePeriod getValidFor() {
    return validFor;
  }

  public void setValidFor(TimePeriod validFor) {
    this.validFor = validFor;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactMediumMVO contactMediumMVO = (ContactMediumMVO) o;
    return Objects.equals(this.preferred, contactMediumMVO.preferred) &&
        Objects.equals(this.contactType, contactMediumMVO.contactType) &&
        Objects.equals(this.validFor, contactMediumMVO.validFor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(preferred, contactType, validFor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactMediumMVO {\n");
    sb.append("    preferred: ").append(toIndentedString(preferred)).append("\n");
    sb.append("    contactType: ").append(toIndentedString(contactType)).append("\n");
    sb.append("    validFor: ").append(toIndentedString(validFor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

