package mx.att.digital.customermanagement.interfaces.dto;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import mx.att.digital.customermanagement.domain.model.EntityRefMVO;
import mx.att.digital.customermanagement.interfaces.dto.BusinessPartnerMVO;
import mx.att.digital.customermanagement.interfaces.dto.CharacteristicMVO;
import mx.att.digital.customermanagement.interfaces.dto.ConsumerMVO;
import mx.att.digital.customermanagement.interfaces.dto.ContactMediumMVO;
import mx.att.digital.customermanagement.interfaces.dto.CreditProfileMVO;
import mx.att.digital.customermanagement.interfaces.dto.Disability;
import mx.att.digital.customermanagement.interfaces.dto.ExternalIdentifierMVO;
import mx.att.digital.customermanagement.interfaces.dto.IndividualIdentificationMVO;
import mx.att.digital.customermanagement.interfaces.dto.IndividualMVO;
import mx.att.digital.customermanagement.interfaces.dto.LanguageAbility;
import mx.att.digital.customermanagement.interfaces.dto.OrganizationChildRelationshipMVO;
import mx.att.digital.customermanagement.interfaces.dto.OrganizationIdentificationMVO;
import mx.att.digital.customermanagement.interfaces.dto.OrganizationMVO;
import mx.att.digital.customermanagement.interfaces.dto.OrganizationParentRelationshipMVO;
import mx.att.digital.customermanagement.interfaces.dto.OtherNameOrganizationMVO;
import mx.att.digital.customermanagement.interfaces.dto.PartyCreditProfileMVO;
import mx.att.digital.customermanagement.interfaces.dto.PartyRefMVO;
import mx.att.digital.customermanagement.interfaces.dto.PartyRoleMVO;
import mx.att.digital.customermanagement.interfaces.dto.PartyRoleRefMVO;
import mx.att.digital.customermanagement.interfaces.dto.ProducerMVO;
import mx.att.digital.customermanagement.interfaces.dto.RelatedPartyOrPartyRoleMVO;
import mx.att.digital.customermanagement.interfaces.dto.Skill;
import mx.att.digital.customermanagement.interfaces.dto.SupplierMVO;
import mx.att.digital.customermanagement.interfaces.dto.TaxExemptionCertificateMVO;
import mx.att.digital.customermanagement.interfaces.dto.TimePeriod;
import org.springframework.format.annotation.DateTimeFormat;
import java.io.Serializable;
import java.time.OffsetDateTime;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import jakarta.annotation.Generated;


@JsonIgnoreProperties(
  value = "@type", // ignore manually set @type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the @type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = BusinessPartnerMVO.class, name = "BusinessPartner"),
  @JsonSubTypes.Type(value = ConsumerMVO.class, name = "Consumer"),
  @JsonSubTypes.Type(value = CustomerMVO.class, name = "Customer"),
  @JsonSubTypes.Type(value = IndividualMVO.class, name = "Individual"),
  @JsonSubTypes.Type(value = OrganizationMVO.class, name = "Organization"),
  @JsonSubTypes.Type(value = PartyRefMVO.class, name = "PartyRef"),
  @JsonSubTypes.Type(value = PartyRoleMVO.class, name = "PartyRole"),
  @JsonSubTypes.Type(value = PartyRoleRefMVO.class, name = "PartyRoleRef"),
  @JsonSubTypes.Type(value = ProducerMVO.class, name = "Producer"),
  @JsonSubTypes.Type(value = SupplierMVO.class, name = "Supplier"),
  @JsonSubTypes.Type(value = BusinessPartnerMVO.class, name = "BusinessPartner_MVO"),
  @JsonSubTypes.Type(value = ConsumerMVO.class, name = "Consumer_MVO"),
  @JsonSubTypes.Type(value = IndividualMVO.class, name = "Individual_MVO"),
  @JsonSubTypes.Type(value = OrganizationMVO.class, name = "Organization_MVO"),
  @JsonSubTypes.Type(value = PartyRefMVO.class, name = "PartyRef_MVO"),
  @JsonSubTypes.Type(value = PartyRoleRefMVO.class, name = "PartyRoleRef_MVO"),
  @JsonSubTypes.Type(value = PartyRoleMVO.class, name = "PartyRole_MVO"),
  @JsonSubTypes.Type(value = ProducerMVO.class, name = "Producer_MVO"),
  @JsonSubTypes.Type(value = SupplierMVO.class, name = "Supplier_MVO")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.10.0")
public interface PartyOrPartyRoleMVO extends Serializable {
    public String getAtType();
}
