package mx.att.digital.customermanagement.interfaces.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import jakarta.annotation.Generated;

import java.io.Serializable;


@JsonIgnoreProperties(
  value = "@type", // ignore manually set @type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the @type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = BusinessPartner.class, name = "BusinessPartner"),
  @JsonSubTypes.Type(value = Consumer.class, name = "Consumer"),
  @JsonSubTypes.Type(value = Customer.class, name = "Customer"),
  @JsonSubTypes.Type(value = Individual.class, name = "Individual"),
  @JsonSubTypes.Type(value = Organization.class, name = "Organization"),
  @JsonSubTypes.Type(value = PartyRef.class, name = "PartyRef"),
  @JsonSubTypes.Type(value = PartyRole.class, name = "PartyRole"),
  @JsonSubTypes.Type(value = PartyRoleRef.class, name = "PartyRoleRef"),
  @JsonSubTypes.Type(value = Producer.class, name = "Producer"),
  @JsonSubTypes.Type(value = Supplier.class, name = "Supplier")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.10.0")
public interface PartyOrPartyRole extends Serializable {
    public String getAtType();
}
