package mx.att.digital.customermanagement.interfaces.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import jakarta.annotation.Generated;

import java.io.Serializable;


@JsonIgnoreProperties(
  value = "@type", // ignore manually set @type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the @type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = BusinessPartnerFVO.class, name = "BusinessPartner"),
  @JsonSubTypes.Type(value = ConsumerFVO.class, name = "Consumer"),
  @JsonSubTypes.Type(value = CustomerFVO.class, name = "Customer"),
  @JsonSubTypes.Type(value = IndividualFVO.class, name = "Individual"),
  @JsonSubTypes.Type(value = OrganizationFVO.class, name = "Organization"),
  @JsonSubTypes.Type(value = PartyRefFVO.class, name = "PartyRef"),
  @JsonSubTypes.Type(value = PartyRoleFVO.class, name = "PartyRole"),
  @JsonSubTypes.Type(value = PartyRoleRefFVO.class, name = "PartyRoleRef"),
  @JsonSubTypes.Type(value = ProducerFVO.class, name = "Producer"),
  @JsonSubTypes.Type(value = SupplierFVO.class, name = "Supplier"),
  @JsonSubTypes.Type(value = BusinessPartnerFVO.class, name = "BusinessPartner_FVO"),
  @JsonSubTypes.Type(value = ConsumerFVO.class, name = "Consumer_FVO"),
  @JsonSubTypes.Type(value = IndividualFVO.class, name = "Individual_FVO"),
  @JsonSubTypes.Type(value = OrganizationFVO.class, name = "Organization_FVO"),
  @JsonSubTypes.Type(value = PartyRefFVO.class, name = "PartyRef_FVO"),
  @JsonSubTypes.Type(value = PartyRoleRefFVO.class, name = "PartyRoleRef_FVO"),
  @JsonSubTypes.Type(value = PartyRoleFVO.class, name = "PartyRole_FVO"),
  @JsonSubTypes.Type(value = ProducerFVO.class, name = "Producer_FVO"),
  @JsonSubTypes.Type(value = SupplierFVO.class, name = "Supplier_FVO")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.10.0")
public interface PartyOrPartyRoleFVO extends Serializable {
    public String getAtType();
}
