# openapi-config-optimized.yaml
basePackage: "mx.att.digital.customermanagement"
apiPackage: "mx.att.digital.customermanagement.interfaces.rest"
modelPackage: "mx.att.digital.customermanagement.interfaces.dto"
invokerPackage: "mx.att.digital.customermanagement.application"
configPackage: "mx.att.digital.customermanagement.infrastructure.configuration"

# Configuración principal
interfaceOnly: false
delegatePattern: true
reactive: true
useSpringBoot3: true
java21: true
dateLibrary: java8-local
serializableModel: true
useBeanValidation: true
useOptional: true

# Generación de aplicación
generateSpringBootApplication: true
applicationName: CustomerManagementApplication
applicationPackage: "mx.att.digital.customermanagement"

# Documentación
hideGenerationTimestamp: true
apiTests: false
modelTests: false
apiDocs: true
modelDocs: true

# Configuraciones específicas
useTags: true
openApiNullable: false
skipDefaultInterface: false
useSpringController: true
useResponseEntity: true

# Mapeos de tipos para TMF629
typeMappings:
  AccountRefFVO: EntityRefFVO
  AgreementRefFVO: EntityRefFVO
  PaymentMethodRefFVO: EntityRefFVO
  AccountRef: EntityRef
  AgreementRef: EntityRef
  PaymentMethodRef: EntityRef
  AccountRefMVO: EntityRefMVO
  AgreementRefMVO: EntityRefMVO
  PaymentMethodRefMVO: EntityRefMVO
  OffsetDateTime: LocalDateTime
  date-time: LocalDateTime

importMappings:
  EntityRefFVO: mx.att.digital.customermanagement.domain.model.EntityRefFVO
  EntityRef: mx.att.digital.customermanagement.domain.model.EntityRef
  EntityRefMVO: mx.att.digital.customermanagement.domain.model.EntityRefMVO
  LocalDateTime: java.time.LocalDateTime

# Configuración para reactive
reactive: true
library: spring-boot
useSpringWebFlux: true

