package mx.att.digital.customermanagement.adapter.in.web.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import jakarta.annotation.Generated;

import java.io.Serializable;


@JsonIgnoreProperties(
  value = "@type", // ignore manually set @type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the @type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = AttachmentMVO.class, name = "Attachment"),
  @JsonSubTypes.Type(value = AttachmentRefMVO.class, name = "AttachmentRef"),
  @JsonSubTypes.Type(value = AttachmentRefMVO.class, name = "AttachmentRef_MVO"),
  @JsonSubTypes.Type(value = AttachmentMVO.class, name = "Attachment_MVO")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.10.0")
public interface AttachmentRefOrValueMVO extends Serializable {
    public String getAtType();
}
