package mx.att.digital.customermanagement.adapter.in.web.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import jakarta.annotation.Generated;

import java.io.Serializable;


@JsonIgnoreProperties(
  value = "@type", // ignore manually set @type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the @type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = BusinessPartnerMVO.class, name = "BusinessPartner"),
  @JsonSubTypes.Type(value = ConsumerMVO.class, name = "Consumer"),
  @JsonSubTypes.Type(value = CustomerMVO.class, name = "Customer"),
  @JsonSubTypes.Type(value = IndividualMVO.class, name = "Individual"),
  @JsonSubTypes.Type(value = OrganizationMVO.class, name = "Organization"),
  @JsonSubTypes.Type(value = PartyRefMVO.class, name = "PartyRef"),
  @JsonSubTypes.Type(value = PartyRoleMVO.class, name = "PartyRole"),
  @JsonSubTypes.Type(value = PartyRoleRefMVO.class, name = "PartyRoleRef"),
  @JsonSubTypes.Type(value = ProducerMVO.class, name = "Producer"),
  @JsonSubTypes.Type(value = SupplierMVO.class, name = "Supplier"),
  @JsonSubTypes.Type(value = BusinessPartnerMVO.class, name = "BusinessPartner_MVO"),
  @JsonSubTypes.Type(value = ConsumerMVO.class, name = "Consumer_MVO"),
  @JsonSubTypes.Type(value = IndividualMVO.class, name = "Individual_MVO"),
  @JsonSubTypes.Type(value = OrganizationMVO.class, name = "Organization_MVO"),
  @JsonSubTypes.Type(value = PartyRefMVO.class, name = "PartyRef_MVO"),
  @JsonSubTypes.Type(value = PartyRoleRefMVO.class, name = "PartyRoleRef_MVO"),
  @JsonSubTypes.Type(value = PartyRoleMVO.class, name = "PartyRole_MVO"),
  @JsonSubTypes.Type(value = ProducerMVO.class, name = "Producer_MVO"),
  @JsonSubTypes.Type(value = SupplierMVO.class, name = "Supplier_MVO")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.10.0")
public interface PartyOrPartyRoleMVO extends Serializable {
    public String getAtType();
}
